//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessNoa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public int LanguageID { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    }
}
