//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessNoa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerVoucherList
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public long VoucherNo { get; set; }
        public bool IsActive { get; set; }
        public string InsertUserName { get; set; }
        public System.DateTime InsertTime { get; set; }
        public string DeleteUserName { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string UsedUserName { get; set; }
        public Nullable<System.DateTime> UsedDatetime { get; set; }
        public bool IsUsed { get; set; }
    }
}
