//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessNoa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerVoucher
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int TotalIn { get; set; }
        public int TotalOut { get; set; }
        public int NetTotal { get; set; }
    }
}
