//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessNoa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int ID { get; set; }
        public int LanguageID { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public int StatusID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> DeleteUserID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> InsertUserID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Content { get; set; }
        public string Keyword { get; set; }
    }
}
