//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningHours
    {
        public int ID { get; set; }
        public string Gun1 { get; set; }
        public string Gun2 { get; set; }
        public string Gun3 { get; set; }
        public string Gun4 { get; set; }
        public string Gun5 { get; set; }
        public string Gun6 { get; set; }
        public string Gun7 { get; set; }
        public int LanguageID { get; set; }
    }
}
