//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageFile
    {
        public int ID { get; set; }
        public int PageID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileURL { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> InsertUserID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> DeleteUserID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
